version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  build: # runs not using Workflows must have a `build` job as entry point
    # working_directory: ~/repo/dist
    docker: # run the steps with Docker
      - image: circleci/golang:1.17

    parallelism: 2

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run: make buildlinux

      - run: cp http-recorder-*.tar.gz /home/circleci/project/dist

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts:
          path: /home/circleci/project/dist

workflows:
  version: 2
  build-workflow:
    jobs:
      - build